/* 
CLASE COMPARTIDA ENTRE CLIENTE Y SERVIDOR.

SE UTILIZA PARA TRANSPORTAR LA INFORMACION NECESARIA
PARA LA INVOCACION REMOTA DE METODOS MEDIANTE UDP SOCKETS.

EL OBJETO CONTIENE:
- EL NOMBRE DEL OBJETO REMOTO
- EL METODO A EJECUTAR
- LOS PARAMETROS NECESARIOS

LA CLASE DEBE SER SERIALIZABLE YA QUE UDP SOLO TRANSPORTA BYTES.
*/

package sheet4.ejercicio8.shared;

public class Message {
    
}
