/* 
REPRESENTA EL PROXY/STUB DEL OBJETO REMOTO.

ESTA CLASE EXISTE SOLO EN EL CLIENTE
Y SIMULA EL COMPORTAMIENTO DE UN Basket REAL.

CUANDO EL CLIENTE LLAMA UN METODO:
- EL PROXY CREA UN Message
- ENVIA LA PETICION POR UDP
- ESPERA LA RESPUESTA DEL SERVIDOR
- RETORNA EL RESULTADO AL CLIENTE

EL PROXY NO CONTIENE LOGICA REAL DE NEGOCIO.
Responsable de: convertir llamadas locales en mensajes UDP.

*/


package sheet4.ejercicio8.client;

public class BasketProxy {
    
}
